version: '3.8'
services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./app:/app/app
      #- ./app/database.sqlite:/app/app/database.sqlite
      - ./app/infrastructure/database/database.sqlite:/app/app/infrastructure/database/database.sqlite
      - ./app/infrastructure/datasets/public_users.xlsx:/app/app/infrastructure/datasets/public_users.xlsx

    #environment:
    #  - SPOTIFY_CLIENT_ID=${SPOTIFY_CLIENT_ID}
    #  - SPOTIFY_CLIENT_SECRET=${SPOTIFY_CLIENT_SECRET}
    #  - REDIRECT_URI=http://127.0.0.1:8888/callback
    #  - LOG_FILE=logs/app.log
    env_file:
      - .env
    stdin_open: true
    tty: true
    develop:
      watch:
        - action: sync
          path: ./app
          target: /app/app
          ignore:
            - "**/__pycache__"
            - "**/*.pyc"
            - "**/.DS_Store"
        - action: rebuild
          path: requirements.txt
