version: '3.8'
services:
  api:
    build: .
    ports:
      - "8888:8888"
    volumes:
      - .:/app
      - ./app:/app/app
    #environment:
    #  - SPOTIFY_CLIENT_ID=${SPOTIFY_CLIENT_ID}
    #  - SPOTIFY_CLIENT_SECRET=${SPOTIFY_CLIENT_SECRET}
    #  - REDIRECT_URI=http://127.0.0.1:8888/callback
    #  - LOG_FILE=logs/app.log
    env_file:
      - .env
    stdin_open: true
    tty: true
